project:
  type: website

website:
  title: "Project Daylight"
  navbar:
    left:
      - text: Proposal
        menu: 
          - text: Proposal
            href: "Proposal/proposal.html"
          - text: Storyboard
            href: "EDA/storyboard.html"
            
      - text: Deliverables
        href: "deliverables.html"
        
      - text: Analysis
        menu: 
          - text: NKDE
            href: "Analysis/NKDE.html"
            
        
        
        
    
    right:
      - href: index.qmd
        text: Home
        
      - text: Github 
        href: "https://github.com/fangqi611/IS415-project" 
        
    


format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

