project:
  type: website

website:
  title: "IS415-project"
  navbar:
    left:
      - text: Proposal
        menu: 
          - text: Proposal
            href: "Proposal/proposal.html"
          - text: Storyboard
            href: "EDA/storyboard.html"
      
      - text: EDA
        href: "EDA/eda.html"
        
      - text: Analysis
        menu: 
          - text: NKDE
            href: "Analysis/NKDE.html"
            
        
        
        
    
    right:
      - href: index.qmd
        text: Home
    


format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

