project:
  type: website

website:
  title: "IS415-project"
  navbar:
    left:
      - text: Proposal
        href: "Proposal/proposal.html"
        
    right:
      - href: index.qmd
        text: Home
    


format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

