---
title: "Project Daylight: Analysing the Recycling Stations in Hong Kong"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
---

Welcome to our website dedicated to our IS415 Geospatial Analytics project! Here, we embark on an exploration of spatial data analysis, leveraging cutting-edge techniques to glean insights from geographic information. Our journey involves delving into diverse datasets, uncovering patterns, and drawing meaningful conclusions. 

To have a better idea on the government’s effort on waste reduction in Hong Kong, we would like to focus on the GREEN\@COMMUNITY initiative promoted by the Environmental Protection Department of Hong Kong. As at mid-February 2024, a total of 11 Recycling Stations, 40 Recycling Stores and over 130 Recycling Spots have been set up throughout the 18 districts in Hong Kong under GREEN\@COMMUNITY for the collection of nine common types of recyclables [(LCQ17: Promoting Waste Reduction and Recycling, 2024) ](https://www.info.gov.hk/gia/general/202402/28/P2024022800418.htm) In our project, we will be analysing the locations of these and evaluate if the coverage of this initiative is sufficient. To go beyond, we will try to come up with solutions on where to add new recycling stations. In the Shiny Application, we will be creating an interactive map with features that users can zoom in/out on the map, do filtering of results and searching functions. 
