---
title: "Our Proposal"
format: html
date-modified: "last-modified"
execute:  
  warning: false
  freeze: true
  message: false 
  eval: true 
  echo: true 
  fig-retine: 3
date: "`r Sys.Date()`"
---

## Problem Statement & Motivation

In the Waste Blueprint 2035 by the Environmental Protection Department [(EPD)](https://www.eeb.gov.hk/sites/default/files/pdf/waste_blueprint_2035_eng.pdf) in 2021, Hong Kong aims to reach a 55% recovery rate as a mid-term target. As of 2022, Hong Kong is at 32% recovery rate. To reach the target in around 10 years time, Hong Kong has to make more efforts in achieving the target in time. 

Given Hong Kong has a very high population density, with 6,740 people per square kilometre , there is a pressing need to assess the distribution and accessibility of recycling stations across the islands. This geospatial analysis aims to investigate whether there are a sufficient number of recycling stations located throughout Hong Kong to effectively serve its population. 

By examining the spatial distribution of existing recycling facilities in relation to population, residential areas, and commercial districts, this study seeks to identify potential gaps in coverage and areas with inadequate access to recycling services. The findings will provide valuable insights for policymakers, urban planners, and waste management authorities to optimise the placement and allocation of recycling infrastructure, ultimately fostering greater participation in recycling efforts and contributing to sustainable waste management practices in Hong Kong.

## Objectives Goals

1.  EDA : reveals the low and high density recycling areas. We can target these areas that are lower in density, figure out the problem of the low recycling and think of solutions to encourage this good habit.

2.  Spatial Point analysis 

    -   First-order (KDE) : Provides insights to the underlying distribution of the data and we can figure out what is causing the low recycling rate, or even test with hypothesis testing.

    -   Second-order (G-Function, F-Function, K-Function) : Quantify the distance of the recycling stations between one another and describe how dispersed the locations are.

3.  Network Constrained Spatial Point Pattern Analysis: Geographical analysis understanding the spatial distribution of events within the context of the network structure, enabling insights and decision-making in various domains of the solution to the recycling problem.

## Data sets

| Title                                                                                | Sources                                                                       | Link                                                                                                                                      |
|---------------------|-------------------|--------------------------------|
| 2021 Population Census Statistics (By District Council District)                     | DATA.GOV.HK.                                                                  | <https://data.gov.hk/en-data/dataset/hk-censtatd-census_geo-2021-population-census-by-dcd/resource/27beef7f-5995-4b79-b3a9-26352c852fda>  |
| Waste Less Recycling Collection Point (By Environmental Protection Department)       | DATA.GOV.HK.                                                                  | <https://data.gov.hk/en-data/dataset/hk-epd-recycteam-waste-less-recyclable-collection-points-data>                                       |
| Land area, mid-year population and population density (By District Council district) | Common Spatial Data Infrastructure (CSDI) - Census and Statistical Department | <https://portal.csdi.gov.hk/geoportal/#metadataInfoPanel>                                                                                 |
| District Boundary                                                                    | Common Spatial Data Infrastructure (CSDI) - Home Affairs Department           | <https://portal.csdi.gov.hk/geoportal/?lang=en&datasetId=had_rcd_1634523272907_75218>                                                     |
| Digital Planning Data of Regulated Areas                                             | Common Spatial Data Infrastructure (CSDI) - Planning Department               | <https://portal.csdi.gov.hk/geoportal/?lang=en&datasetId=c17a8a39-4fed-5e02-8528-998b84011228>                                            |

## Literature Review

| Title                                                                                                         | Summarize                                                                                                                                                                                                                                | Sources                                                                                                                   |
|------------------|----------------------------------|-------------------|
| With Hong Kong running out of space for its trash, residents are doing more to reduce food waste              | This article talks about how Hong Kong does not have enough space for landfills due to their country’s size and also because of the trouble people have to go through to recycle, which prevents them from cultivating such good habits. | <https://www.channelnewsasia.com/asia/hong-kong-landfills-running-out-space-3217566>                                      |
| How Hong Kong’s already-serious waste problem has got worse during the pandemic                               | This article talks about how the recycling problem in Hong Kong has been a pressing issue in the state since 1997 and it is only getting worse for them due to the lack of effort and limited land space.                                | <https://www.scmp.com/comment/opinion/article/3160067/how-hong-kongs-already-serious-waste-problem-has-got-worse-during>  |
| WASTE BLUEPRINT for Hong Kong 2035 Environmental Protection Department. (n.d.).                               | The goals and targets that HKGOV wish to reach in terms of waste reduction in 2035.                                                                                                                                                      | <https://www.eeb.gov.hk/sites/default/files/pdf/waste_blueprint_2035_eng.pdf>                                             |
| MONITORING OF SOLID WASTE IN HONG KONG Waste Statistics for 2022 Environmental Protection Department. (n.d.). | The statistics of HK in solid waste in 2022.                                                                                                                                                                                             | <https://www.wastereduction.gov.hk/sites/default/files/resources_centre/waste_statistics/msw2022_eng.pdf>                 |

## Feature of our Application

Out application will include an interactive map display for users to look out for nearby recycling locations under the GREEN\@Community initiative. Users can zoom in and out on the map to have a better idea on their locations. They can filter out different recycling locations by selecting which districts/ neighbourhoods they wish to visit. The app will also allow users to search in a search bar for a specific location. The data in the app will help the Hong Kong government to understand citizens’ recycling habits to encourage them more through their lifestyle.

## Timeline

| Week | Milestones                                         |
|------|----------------------------------------------------|
| 8    | Data Cleaning, EDA                                 |
| 9    | Spatial Point analysis, First Order                |
| 10   | Spatial Point analysis, Second Order               |
| 11   | Network Constrained Spatial Point Pattern Analysis |
| 12   | Finishing up and tidying up                        |
| 13   | Finalizing, printing the poster                    |
| 14   | Presentation                                       |

## References

1.  LCQ17: Promoting waste reduction and recycling. (2024). Info.gov.hk. <https://www.info.gov.hk/gia/general/202402/28/P2024022800418.htm> ‌
2.  LCQ12: Operation of the community recycling network GREEN\@COMMUNITY. (2023). Info.gov.hk. <https://www.info.gov.hk/gia/general/202402/28/P2024022800306.htm>
3.  GovHK (www.gov.hk. (2024, January 16). GovHK: Hong Kong – the Facts. Www.gov.hk. <https://www.gov.hk/en/about/abouthk/facts.htm> 
